using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using System.Xml.Serialization;

namespace Bing.CodeGenerator.Core
{
    /// <summary>
    /// 属性
    /// </summary>
    public class Property : EntityBase
    {
        /// <summary>
        /// 属性名
        /// </summary>
        public string PropertyName { get; set; }

        /// <summary>
        /// 列名
        /// </summary>
        public string ColumnName { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// 数据类型
        /// </summary>
        public DbType DataType { get; set; }

        /// <summary>
        /// 原生类型
        /// </summary>
        public string NativeType { get; set; }

        /// <summary>
        /// 系统类型
        /// </summary>
        [XmlIgnore]
        public Type SystemType { get; set; }

        /// <summary>
        /// 排序
        /// </summary>
        public int? Order { get; set; }

        /// <summary>
        /// 是否指定排序
        /// </summary>
        public bool OrderSpecified => Order.HasValue;

        /// <summary>
        /// 是否可空值
        /// </summary>
        public bool? IsNullable { get; set; }

        /// <summary>
        /// 是否指定可空值
        /// </summary>
        public bool IsNullableSpecified => IsNullable.HasValue;

        /// <summary>
        /// 是否必填项
        /// </summary>
        public bool IsRequired
        {
            get => IsNullable == false;
            set => IsNullable = !value;
        }

        /// <summary>
        /// 是否可选项
        /// </summary>
        public bool IsOptional
        {
            get => IsNullable == true;
            set => IsNullable = value;
        }

        /// <summary>
        /// 是否主键
        /// </summary>
        public bool? IsPrimaryKey { get; set; }

        /// <summary>
        /// 是否指定主键
        /// </summary>
        public bool IsPrimaryKeySpecified => IsPrimaryKey.HasValue;

        /// <summary>
        /// 是否外键
        /// </summary>
        public bool? IsForeignKey { get; set; }

        /// <summary>
        /// 是否指定外键
        /// </summary>
        public bool IsForeignKeySpecified => IsForeignKey.HasValue;

        /// <summary>
        /// 是否自动生成
        /// </summary>
        public bool? IsAutoGenerated { get; set; }

        /// <summary>
        /// 是否指定自动生成
        /// </summary>
        public bool IsAutoGeneratedSpecified => IsAutoGenerated.HasValue;

        /// <summary>
        /// 是否只读
        /// </summary>
        public bool? IsReadOnly { get; set; }

        /// <summary>
        /// 是否指定只读
        /// </summary>
        public bool IsReadOnlySpecified => IsReadOnly.HasValue;

        /// <summary>
        /// 是否行版本
        /// </summary>
        public bool? IsRowVersion { get; set; }

        /// <summary>
        /// 是否指定行版本
        /// </summary>
        public bool IsRowVersionSpecified => IsRowVersion.HasValue;

        /// <summary>
        /// 是否自增列
        /// </summary>
        public bool? IsIdentity { get; set; }

        /// <summary>
        /// 是否指定自增列
        /// </summary>
        public bool IsIdentitySpecified => IsIdentity.HasValue;
    }
}
