Module: Erp
Author: jian玄冰
DataSource:
  Name: DbTableSchema
  Parameters:
    DbName: Erp
    DbProvider: SqlServer
    ConnectionString: Data Source=;Initial Catalog=Erp;User Id=sa;Password=Bing2019.00;
Language: CSharp
TemplateEngine:
  Name: RazorTest
  Root: Util
  Path: G:\Git\SmartCode\Bing.GenerateDemo\bin\Debug\netcoreapp2.2\RazorTemplates
Output:
  Type: File
  Path: 'D:\demo\generate'
Parameters:
  UnitOfWork: Erp

NamingConverter:
  Table:
    Tokenizer:
      Type: Default
    Converter:
      Type: Default
  View:
    Tokenizer:
      Type: Default
    Converter:
      Type: Default
  Column:
    Tokenizer:
      Type: Default
    Converter:
      Type: Default
# 构建任务
Build:
  # 清空目录
  ClearDir:
    Type: Clear
    Parameters:
      Dirs: '.'
  # 脚手架
  Scaffolding:
    Type: MultiTemplate
    Output:
      Path: '.'
    Parameters:
      Templates: [
      {Key: 'Datas/IUnitOfWork.cshtml', Output: { Path: 'Datas', Name: 'I{{Project.Parameters.UnitOfWork}}UnitOfWork', Extension: '.cs'}},
      {Key: 'Datas/MySql/UnitOfWork.cshtml', Output: { Path: 'Datas/UnitOfWorks/MySql', Name: '{{Project.Parameters.UnitOfWork}}UnitOfWork', Extension: '.cs'}},
      {Key: 'Datas/PgSql/UnitOfWork.cshtml', Output: { Path: 'Datas/UnitOfWorks/PgSql', Name: '{{Project.Parameters.UnitOfWork}}UnitOfWork', Extension: '.cs'}},
      {Key: 'Datas/SqlServer/UnitOfWork.cshtml', Output: { Path: 'Datas/UnitOfWorks/SqlServer', Name: '{{Project.Parameters.UnitOfWork}}UnitOfWork', Extension: '.cs'}}, ]
  
  # 项分组
  ItemGroup:
    Type: Schema
    Module: ItemGroup
    TemplateEngine:
      Path: Domains/ItemGroup.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}'
      Name: 'ItemGroup'
      Extension: '.txt'
  
  # 仓储生成
  RepositoryInterface:
    Type: SchemaTable
    Module: Repositories
    TemplateEngine:
      Path: Domains/IRepository.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}/{{Build.Module}}'
      Name: 'I{{Items.CurrentTable.ConvertedName}}Repository'
      Extension: '.cs'
  RepositoryImpl:
    Type: SchemaTable
    Module: Repositories
    TemplateEngine:
      Path: Datas/Repository.cshtml
    Output:
      Path: 'Datas/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Repository'
      Extension: '.cs'
  
  # 实体生成
  Entity:
    Type: SchemaTable
    Module: Models
    TemplateEngine:
      Path: Domains/Entity.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}/{{Build.Module}}'
      Name: '{{Items.CurrentTable.ConvertedName}}'
      Extension: '.cs'
  EntityBase:
    Type: SchemaTable
    Module: Models
    TemplateEngine:
      Path: Domains/Entity.Common.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}/{{Build.Module}}'
      Name: '{{Items.CurrentTable.ConvertedName}}.Base'
      Extension: '.cs'
  
  # 工厂生成
  Factory:
    Type: SchemaTable
    Module: Factories
    TemplateEngine:
      Path: Domains/Factory.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}/{{Build.Module}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Factory'
      Extension: '.cs'
  
  # 领域服务生成
  DomainServiceInterface:
    Type: SchemaTable
    Module: Services
    TemplateEngine:
      Path: Domains/IDomainService.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}/{{Build.Module}}/Abstractions'
      Name: 'I{{Items.CurrentTable.ConvertedName}}Manager'
      Extension: '.cs'
  DomainServiceImpl:
    Type: SchemaTable
    Module: Services
    TemplateEngine:
      Path: Domains/DomainService.cshtml
    Output:
      Path: 'Domains/{{Items.CurrentSchema.Name}}/{{Build.Module}}/Implements'
      Name: '{{Items.CurrentTable.ConvertedName}}Manager'
      Extension: '.cs'
  
  # 映射生成
  MySqlMapping:
    Type: SchemaTable
    Module: Mappings
    TemplateEngine:
      Path: Datas/MySql/Mapping.cshtml
    Output:
      Path: 'Datas/{{Build.Module}}/{{Items.CurrentSchema.Name}}/MySql'
      Name: '{{Items.CurrentTable.ConvertedName}}Map'
      Extension: '.cs'
  PgSqlMapping:
    Type: SchemaTable
    Module: Mappings
    TemplateEngine:
      Path: Datas/PgSql/Mapping.cshtml
    Output:
      Path: 'Datas/{{Build.Module}}/{{Items.CurrentSchema.Name}}/PgSql'
      Name: '{{Items.CurrentTable.ConvertedName}}Map'
      Extension: '.cs'
  SqlServerMapping:
    Type: SchemaTable
    Module: Mappings
    TemplateEngine:
      Path: Datas/SqlServer/Mapping.cshtml
    Output:
      Path: 'Datas/{{Build.Module}}/{{Items.CurrentSchema.Name}}/SqlServer'
      Name: '{{Items.CurrentTable.ConvertedName}}Map'
      Extension: '.cs'
  
  # 数据传输对象生成
  Dto:
    Type: SchemaTable
    Module: Dtos
    TemplateEngine:
      Path: Services/Dto.cshtml
    Output:
      Path: 'Services/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Dto'
      Extension: '.cs'
  DtoExtensions:
    Type: SchemaTable
    Module: Extensions
    TemplateEngine:
      Path: Services/DtoExtensions.cshtml
    Output:
      Path: 'Services/Dtos/{{Items.CurrentSchema.Name}}/{{Build.Module}}'
      Name: 'Extensions.{{Items.CurrentTable.ConvertedName}}'
      Extension: '.cs'
  Query:
    Type: SchemaTable
    Module: Queries
    TemplateEngine:
      Path: Services/Query.cshtml
    Output:
      Path: 'Services/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Query'
      Extension: '.cs'
  
  # 服务生成
  ServiceInterface:
    Type: SchemaTable
    Module: Abstractions
    TemplateEngine:
      Path: Services/IService.cshtml
    Output:
      Path: 'Services/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: 'I{{Items.CurrentTable.ConvertedName}}Service'
      Extension: '.cs'
  ServiceImpl:
    Type: SchemaTable
    Module: Implements
    TemplateEngine:
      Path: Services/Service.cshtml
    Output:
      Path: 'Services/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Service'
      Extension: '.cs'
  SimpleServiceInterface:
    Type: SchemaTable
    Module: Abstractions
    TemplateEngine:
      Path: Services/Simple/IService.cshtml
    Output:
      Path: 'Services_Simple/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: 'I{{Items.CurrentTable.ConvertedName}}Service'
      Extension: '.cs'
  SimpleServiceImpl:
    Type: SchemaTable
    Module: Implements
    TemplateEngine:
      Path: Services/Simple/Service.cshtml
    Output:
      Path: 'Services_Simple/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Service'
      Extension: '.cs'
  SimpleQueryServiceInterface:
    Type: SchemaTable
    Module: Abstractions
    TemplateEngine:
      Path: Services/Queries/IQueryService.cshtml
    Output:
      Path: 'Services_Simple/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: 'IQuery{{Items.CurrentTable.ConvertedName}}Service'
      Extension: '.cs'
  SimpleQueryServiceImpl:
    Type: SchemaTable
    Module: Implements
    TemplateEngine:
      Path: Services/Queries/QueryService.cshtml
    Output:
      Path: 'Services_Simple/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: 'Query{{Items.CurrentTable.ConvertedName}}Service'
      Extension: '.cs'

  # 表现层生成
  ApiController:
    Type: SchemaTable
    Module: Apis
    TemplateEngine:
      Path: Presentation/ApiController.cshtml
    Output:
      Path: 'Presentation/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Controller'
      Extension: '.cs'
  SimpleApiController:
    Type: SchemaTable
    Module: Apis
    TemplateEngine:
      Path: Presentation/Simple/ApiController.cshtml
    Output:
      Path: 'Presentation_Simple/{{Build.Module}}/{{Items.CurrentSchema.Name}}'
      Name: '{{Items.CurrentTable.ConvertedName}}Controller'
      Extension: '.cs'